#config.yml
mensajes:
  activar-titulo: true #Mensaje de entrada / true = Si false = no
  mensaje-titulo: "&a¡Bienvenid@!" #Titulo del mensaje de entrada.
  mensaje-subtitulo: "&e%player%&5, estas listo." #Subtitulo del mensaje de entrada.
  mensaje-entrada: "&f&l[&a&l+&f&l] &r&6%player%" #Mensaje para cuando entra un jugador del servidor
  activar-entrada: true #Entrada customizada de DreamServer / true = Si false = no
  entrada-default: false #Entrada por defecto de Minecraft / true = Si false = no
  activar-salida: true #Salida customizada de DreamServer / true = Si false = no
  salida-default: false #Salida por defecto de Minecraft / true = Si false = no
  mensaje-salida: "&f&l[&4&l-&f&l] &r&6%player%" #Mensaje para cuando sale un jugador del servidor.
  comando-incorrecto: "&cUso incorrecto, por favor use: /ds ayuda" #Error para cuando el comando haya sido mal escrito.
  comando-tiempo-dia: "&aHas cambiado el tiempo a dia." #Mensaje que se enviara cuando se cambie el tiempo a dia.
  comando-tiempo-noche: "&aHas cambiado el tiempo a noche." #Mensaje que se enviara cuando se cambie el tiempo a noche.
  comando-tiempo-medianoche: "&aHas cambiado el tiempo a medianoche." #Mensaje que se enviara cuando se cambie el tiempo a medianoche.
  comando-tiempo-amanecer: "&aHas cambiado el tiempo a amanecer." #Mensaje que se enviara cuando se cambie el tiempo a amanecer.
  comando-tiempo-mediodia: "&aHas cambiado el tiempo a mediodia." #Mensaje que se enviara cuando se cambie el tiempo a mediodia.
  comando-tiempo-atardecer: "&aHas cambiado el tiempo a atardecer." #Mensaje que se enviara cuando se cambie el tiempo a atardecer.
  comando-clima-soleado: "&aHas cambiado el clima a soleado." #Mensaje que se enviara cuando se cambie el clima a soleado.
  comando-clima-lluvioso: "&aHas cambiado el clima a lluvioso." #Mensaje que se enviara cuando se cambie el clima a lluvioso.
  comando-clima-tormentoso: "&aHas cambiado el clima a tormentoso." #Mensaje que se enviara cuando se cambie el clima a tormentoso.
  error-no-jugador: "&cNo eres un jugador >=/" #Mensaje que se enviara si la consola intenta ejecutar un comando para jugadores.
  puntoincial-guardado: "&aPunto inicial guardado correctamente." #Mensaje que se enviara cuando se establezca el puntoinicial.
  error-no-inicio: "&cNo se ha establecido un punto inicial aun." #Error para cuando el jugador intente ir a inicio y este no este establecido.
  tp-inicio: "&aHas sido teletransportado a inicio." #Mensaje que se enviara cuando se teletransporte a inicio.
  error-no-mundo: "&cEl mundo proporcionado no existe." #Error para cuando el mundo especificado no exista.
  tp-mundo: "&aHas sido teletransportado al mundo." #Mensaje que se enviara cuando se teletransporte a un mundo.
  no-tnt: "&cNo esta permitido lanzar TNT." #Mensaje que se enviara cuando se intente explotar una tnt y no este activada.
  no-cristales: "&cNo esta permitido explotar cristales." #Mensaje que se enviara cuando se intente explotar un cristal del end y no este activado.
  no-creepers: "&cNo esta permitido explotar creepers." #Mensaje que se enviara cuando se intente explotar un creeper y no este activado.
  teleport-cama: "&aTeletransportando a tu cama..." #Mensaje que se enviara cuando se teletransporte a la cama.
  error-cama: "&cNo tienes cama." #Error para cuando el jugador no tiene cama.
  tp-punto: "&aTe has teletransportado a %point%" #Mensaje que se enviara cuando te teletransportes a un punto.
  error-punto: "&cNo existe %point%" #Error para cuando no existe el punto seleccionado.
  error-permisos: "&cNo tienes permisos para esto!" #Error para cuando no tienes permisos.
  error-reglas: "&cNo se encontro el archivo reglas.txt" #Error para cuando no hay reglas.txt
  error-no-material: "&cNo tienes ningun material en la mano." #Error para cuando no tienes un material en la mano.
  error-no-renombrable: "&cEste item no se puede renombrar." #Error para cuando no puedes renombrar un item.
  renombrado: "&aTu item ha sido renombrado a: &5%display_name%&a." #Mensaje que se enviara cuando renombres un item.
  descripcion-aplicada: "&aLa descripcion de tu item ha cambiado a: &3%lore%&a." #Mensaje que se enviara cuando cambies la descripcion de un item.
  tag-cambiado: "&aTu nombre ahora es: %name%" #Mensaje que se enviara cuando cambies tu nombre.
  error-tener-brillo: "&cEste item no puede tener brillo." #Error para cuando el item no puede brillar
  brillo_off: "&aBrillo desactivado." #Mensaje que se enviara cuando desactives el brillo de un item.
  brillo_on: "&aBrillo activado" #Mensaje que se enviara cuando actives el brillo de un item.
  error-nick-no-encontrado: "&cJugador no encontrado." #Error para cuando un nick no es encontrado
  permiso-asignado: "&aPermiso &e%perm% &aasignado a &e%player%&a." #Mensaje que se enviara cuando se asigne un permiso.
  permisos-desasignado: "&cPermiso &5%perm% &cdesasignado de &5%player%&c." #Mensaje que se enviara cuando se desasigne un permiso.
  err-holo-id: "&cEsa ID ya existe." #Error para cuando una id de NPC ya existe.
  err-holo-null: "&cNo existe esa ID." #Error para cuando una ID de Holograma no existe.
  holo-creado: "&aHolograma creado correctamente." #Mensaje que se enviara cuando se cree un NPC
  holo-eliminado: "&cHolograma eliminado correctamente." #Mensaje que se enviara cuando se elimine un Holograma.
antilag:
  activado: true #AntiLag, eliminar items del suelo. / true = Si false = no
  segundos: 120 #Cada cuantos segundos se ejecuta?
  monitorearping: true #Esto avisa cuando el servidor va con retraso / true = Si false = no
efectos:
  cohete-bienvenida: true #Cohete que se activara cuando entre alguien al servidor / true = Si false = no
  sonido-bienvenida: true #Sonido que se activara cuando entre alguien al servidor / true = Si false = no
explosivos:
  activar-tnt: true #Activar la TNT / true = Si false = no
  activar-cristales: true #Activar cristales del end / true = Si false = no
  activar-creepers: true #Activar creepers / true = Si false = no
bloqueo-palabras:
  activado: true #Activar el bloqueo de palabras / true = Si false = No
  lista: #Insertar aqui todas las palabras bloqueadas
    - ostia
    - puta
    - mierda
  mensaje: "&c¡Lenguaje no permitido!" #Mensaje que recibira el jugador cuando diga alguna de las palabras anteriores
#NO TOCAR
version: "1.1.2"